### ISSUE TITLE
Send gem report to Slack

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/access-update-scripts#13]
Jenkins --> Slack plugin

**Comment by jkeck** [comment]
By `Gem Report` do we mean the list of repos and links to their dependency update PRs, or do we mean the output that comes from `autupdate.sh`? https://github.com/sul-dlss/access-update-scripts/blob/832ebb18069148de931750c796afe86ec4aab191/autupdate.sh#L69-L73

Just trying to figure out if this will be accomplished by #15 or if there will be more work to be done to close this out.

**Comment by camillevilla** [comment]
@jkeck yep! We want a quick summary of gems updated and whether they were patch, minor, or major updates.

**Comment by jkeck** [comment]
Okay, I'll add a follow on PR to send that content to Slack.
