### ISSUE TITLE
Add infrastructure repositories to the update list

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/access-update-scripts#19]

**Comment by cbeer** [comment]
Here's a thought that might take minimal process changes, at least...

what if we add another build stage or step for infrastructure:
https://github.com/sul-dlss/access-update-scripts/blob/master/Jenkinsfile#L15

And just set or pass in the necessary configuration?

**Comment by jkeck** [comment]
@cbeer I was imagining something similar.
